credentials:
  usernames:
    jsmith:
      email: jsmith@gmail.com
      name: John Smith
      password: '$2b$12$LNYydJk3efqhEV9ZJpCNGeg4fm1pon19p4zsdV9zQ9pgrYTTvJtyy'
      role: 'Manager'
    rbriggs:
      email: rbriggs@gmail.com
      name: Rebecca Briggs
      password: '$2b$12$LNYydJk3efqhEV9ZJpCNGeg4fm1pon19p4zsdV9zQ9pgrYTTvJtyy'
      role: 'Representative'
    testuser:
      email: test@test.com
      name: Test User
      password: '$2b$12$LNYydJk3efqhEV9ZJpCNGeg4fm1pon19p4zsdV9zQ9pgrYTTvJtyy'
      role: 'Representative'
cookie:
  expiry_days: 30
  key: some_random_key
  name: some_cookie_name_v2
preauthorized:
  emails:
  - friend@example.com
